version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: calmcompanion-backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./requirements.txt:/tmp/requirements.txt:ro
      - ./.env:/app/.env:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: calmcompanion-frontend
    env_file:
      - .env
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app/frontend
      - ./requirements.txt:/tmp/requirements.txt:ro
      - ./.env:/app/.env:ro
    depends_on:
      backend:
        condition: service_healthy

  voice_pwa:
    build:
      context: .
      dockerfile: voice_pwa/Dockerfile
    container_name: calmcompanion-voice-pwa
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./voice_pwa:/app
      - ./.env:/app/.env:ro
    depends_on:
      backend:
        condition: service_healthy
